version: '3'
services:
  app:
    container_name: full_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - .:/usr/src/app
    depends_on:
      - task-postgres
      - redis
    networks:
      - golang-task

  task-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5433:5432'
    volumes:
      - task_postgres:/var/lib/postgresql/data
    networks:
      - golang-task
  
  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    volumes:
      - redis:/bitnami/redis
    ports:
      - 6379
    networks:
      - golang-task
    
volumes:
  api:
  task_postgres:
  redis:

networks:
  golang-task:
    driver: bridge
